export type LevelId = "infantil" | "fundamental" | "medio" | "enem" | "vestibular" | "concurso" | "reciclagem";
export type SubjectId = "portugues" | "matematica" | "redacao" | "logica" | "metodologia";
export type LessonStep = { title: string; body: string; speak?: string };
export type Lesson = { id: string; title: string; subject: SubjectId; levels: LevelId[]; minutes: number; summary: string; steps: LessonStep[] };
export const SUBJECT_LABEL: Record<SubjectId,string> = { portugues:"Português", matematica:"Matemática", redacao:"Redação", logica:"Raciocínio lógico", metodologia:"Metodologia" };
export const LEVEL_LABEL: Record<LevelId,string> = { infantil:"Alfabetização", fundamental:"Fundamental", medio:"Ensino médio", enem:"ENEM", vestibular:"Vestibular", concurso:"Concursos", reciclagem:"Reciclagem" };
export const LESSONS: Lesson[] = [
 { id:"vogais", title:"As vogais que abrem a leitura", subject:"portugues", levels:["infantil","reciclagem"], minutes:12, summary:"A, E, I, O, U: o som que faz a boca abrir e as palavras nascerem.", steps:[{title:"Cinco letras, cinco sons",body:"As vogais são A, E, I, O e U. Toda sílaba em português precisa de uma vogal."},{title:"A boca muda o som",body:"A boca e os lábios mudam o som de cada vogal. Repetir o gesto ajuda a gravar."}]},
 { id:"fracoes", title:"Frações equivalentes", subject:"matematica", levels:["fundamental","medio","reciclagem"], minutes:16, summary:"Mesmo pedaço da unidade, escrito de formas diferentes.", steps:[{title:"O que a fração conta",body:"O denominador indica em quantas partes iguais a unidade foi dividida; o numerador indica quantas partes consideramos."},{title:"Equivalência",body:"Multiplique ou divida numerador e denominador pelo mesmo número diferente de zero: 1/2 = 2/4 = 3/6."}]},
 { id:"funcao-afim", title:"Função afim: y = ax + b", subject:"matematica", levels:["medio","enem","vestibular","reciclagem"], minutes:18, summary:"Reta no plano: a indica a inclinação e b o valor de y quando x é zero.", steps:[{title:"Ler os coeficientes",body:"Em y = ax + b, a mostra se a reta sobe, desce ou é horizontal; b é o intercepto no eixo y."},{title:"Zero da função",body:"Se a ≠ 0, o zero ocorre em x = −b/a. No ENEM, observe onde o gráfico cruza o eixo x."}]},
 { id:"interpretacao-enem", title:"Interpretação de texto no ENEM", subject:"portugues", levels:["medio","enem","vestibular","reciclagem"], minutes:16, summary:"A resposta deve ser autorizada pelo texto, não por um achismo.", steps:[{title:"Ler o comando",body:"Identifique se a questão pede tese, inferência, pressuposto, ironia ou função da linguagem."},{title:"Eliminar com método",body:"Risque alternativas que contradizem ou inventam informação. Escolha a paráfrase mais fiel ao texto."}]},
 { id:"redacao-enem", title:"Redação: as 5 competências", subject:"redacao", levels:["medio","enem","vestibular","reciclagem"], minutes:22, summary:"Norma, tema, projeto de texto, coesão e proposta de intervenção.", steps:[{title:"Mapa das competências",body:"Treine norma, tema/repertório, argumentação, coesão e intervenção separadamente e depois integre."},{title:"Intervenção",body:"Uma proposta completa identifica agente, ação, meio, efeito e detalhamento."}]},
 { id:"logica-concursos", title:"Raciocínio lógico: negação", subject:"logica", levels:["concurso","vestibular","reciclagem"], minutes:20, summary:"Negação e equivalência de proposições para provas e concursos.", steps:[{title:"Condicional",body:"p → q só é falsa quando p é verdadeira e q é falsa. A contrapositiva é equivalente: ~q → ~p."},{title:"Como negar",body:"A negação de p → q é p ∧ ~q. Evite trocar simplesmente os sinais."}]},
 { id:"abnt-tcc", title:"Esqueleto de um TCC", subject:"metodologia", levels:["medio","vestibular","reciclagem"], minutes:18, summary:"Capa, elementos textuais, referências e organização metodológica.", steps:[{title:"Pré-textuais",body:"Organize capa, folha de rosto, resumo, palavras-chave e sumário conforme a instituição."},{title:"Textuais",body:"Alinhe problema, objetivos, justificativa, método, desenvolvimento e conclusão."}]}
];
export function lessonById(id: string | undefined | null){ return id ? LESSONS.find((lesson)=>lesson.id===id) : undefined; }
export function lessonsFor(level?: LevelId, subject?: SubjectId){ return LESSONS.filter((lesson)=>(!level || lesson.levels.includes(level)) && (!subject || lesson.subject===subject)); }