import { createFileRoute } from "@tanstack/react-router";
import { Bot, BrainCircuit, CheckCircle2, Database, Layers3, Play, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { EDUCATION_AREAS, EDUCATION_LEVELS } from "@/lib/education-universe";
import { generateLesson } from "@/lib/ai-rag";

export const Route = createFileRoute("/ia")({ component: IALabPage, head: () => ({ meta: [{ title: "Heureca AI Lab — Superlativo Heureca" }] }) });

function IALabPage() {
  const [topic, setTopic] = useState("Função afim");
  const [goal, setGoal] = useState("compreender e resolver exercícios");
  const [level, setLevel] = useState("Ensino Médio");
  const [area, setArea] = useState("Matemática");
  const [lesson, setLesson] = useState(() => generateLesson({ topic: "Função afim", goal: "compreender e resolver exercícios", level: "Ensino Médio", area: "Matemática" }));
  const [running, setRunning] = useState(false);
  const context = useMemo(() => lesson.sources.map((s) => s.title).join(" · "), [lesson.sources]);
  function create() { setRunning(true); window.setTimeout(() => { setLesson(generateLesson({ topic, goal, level, area })); setRunning(false); }, 350); }
  return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
    <section className="overflow-hidden rounded-[2rem] bg-navy-deep p-6 text-white shadow-card sm:p-9"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-gold"><Sparkles className="size-4" /> Heureca AI Lab</p><h1 className="mt-3 font-display text-4xl font-semibold leading-tight sm:text-6xl">Crie, explore e aprenda com IA.</h1><p className="mt-4 max-w-2xl text-base leading-relaxed text-white/75 sm:text-lg">Um estúdio de aulas dinâmicas que combina recuperação de conhecimento (RAG), planejamento pedagógico e geração de atividades. A experiência começa localmente e já está preparada para receber um provedor GenAI real.</p></div><div className="grid size-16 place-items-center rounded-2xl bg-white/10 text-gold"><BrainCircuit className="size-8" /></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[{ icon: Database, title: "RAG", text: "recupera contexto relevante" }, { icon: Bot, title: "GenAI", text: "compõe uma aula adaptável" }, { icon: Layers3, title: "Memória", text: "estrutura para evolução por perfil" }].map((item) => <div key={item.title} className="rounded-2xl border border-white/10 bg-white/5 p-4"><item.icon className="size-5 text-gold" /><p className="mt-3 font-semibold">{item.title}</p><p className="mt-1 text-sm text-white/60">{item.text}</p></div>)}</div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[0.82fr_1.18fr]"><div className="rounded-[1.6rem] bg-surface p-5 shadow-card sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-magenta">Criador de aula</p><h2 className="mt-2 font-display text-2xl font-semibold text-navy">Defina a missão</h2><label className="mt-5 block text-xs font-bold uppercase tracking-[0.12em] text-muted" htmlFor="tema">Tema</label><input id="tema" value={topic} onChange={(e) => setTopic(e.target.value)} className="mt-1 h-12 w-full rounded-xl bg-paper px-3 text-sm" placeholder="Ex.: fotossíntese, crase, estatística..." /><label className="mt-4 block text-xs font-bold uppercase tracking-[0.12em] text-muted" htmlFor="objetivo">Objetivo</label><input id="objetivo" value={goal} onChange={(e) => setGoal(e.target.value)} className="mt-1 h-12 w-full rounded-xl bg-paper px-3 text-sm" placeholder="O que quero dominar?" /><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="block text-xs font-bold uppercase tracking-[0.12em] text-muted" htmlFor="nivel">Nível</label><select id="nivel" value={level} onChange={(e) => setLevel(e.target.value)} className="mt-1 h-12 w-full rounded-xl bg-paper px-3 text-sm">{EDUCATION_LEVELS.map((item) => <option key={item.id}>{item.title}</option>)}</select></div><div><label className="block text-xs font-bold uppercase tracking-[0.12em] text-muted" htmlFor="area">Área</label><select id="area" value={area} onChange={(e) => setArea(e.target.value)} className="mt-1 h-12 w-full rounded-xl bg-paper px-3 text-sm">{EDUCATION_AREAS.map((item) => <option key={item.id}>{item.title}</option>)}</select></div></div><Button type="button" className="mt-5 w-full" onClick={create} disabled={running}><Play className="size-4" />{running ? "Construindo..." : "Criar aula com IA"}</Button><div className="mt-5 rounded-2xl bg-mist p-4 text-sm text-navy"><p className="font-bold">Pipeline ativo</p><p className="mt-1 text-navy/70">Pergunta → recuperação RAG → contexto → aula → prática.</p></div></div>
      <article className="rounded-[1.6rem] bg-white p-5 shadow-card sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-magenta">Aula gerada</p><h2 className="mt-2 font-display text-3xl font-semibold text-navy">{lesson.title}</h2></div><span className="rounded-full bg-blush px-3 py-1 text-xs font-bold text-magenta-deep">{lesson.duration}</span></div><p className="mt-4 rounded-2xl bg-paper p-4 leading-relaxed text-ink/80"><strong className="text-navy">Objetivo:</strong> {lesson.objective}</p><div className="mt-5 space-y-3">{lesson.steps.map((step) => <section key={step.title} className="rounded-2xl border border-line p-4"><h3 className="font-semibold text-navy">{step.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted">{step.body}</p></section>)}</div><div className="mt-5"><h3 className="font-display text-xl font-semibold text-navy">Prática inteligente</h3><ul className="mt-2 space-y-2">{lesson.practice.map((item) => <li key={item} className="flex gap-2 text-sm text-muted"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-magenta" />{item}</li>)}</ul></div><div className="mt-6 rounded-2xl bg-navy p-4 text-white"><p className="text-xs font-bold uppercase tracking-[0.14em] text-gold">Contexto recuperado pelo RAG</p><p className="mt-2 text-sm text-white/75">{context}</p></div></article></section>
    <p className="mt-6 text-xs leading-relaxed text-muted">Nota técnica: esta entrega implementa o motor RAG demonstrativo no navegador. Para GenAI em produção, conecte um modelo autorizado e uma base documental com autenticação, controle de acesso, logs e políticas de privacidade. A ferramenta apoia o estudante; não substitui autoria, orientação institucional ou avaliação profissional.</p>
  </div>;
}