import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, GraduationCap, Microscope, Scale, School, Sparkles } from "lucide-react";
import { ACADEMIC_SERVICES, EDUCATION_AREAS, EDUCATION_LEVELS } from "@/lib/education-universe";

export const Route = createFileRoute("/universo")({ component: UniversoPage, head: () => ({ meta: [{ title: "Universo Educacional — Superlativo Heureca" }] }) });
const ICONS = [GraduationCap, School, Microscope, Scale, BookOpenCheck, Sparkles, GraduationCap];

function UniversoPage() {
  return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
    <section className="rounded-[2rem] bg-navy p-6 text-white shadow-card sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold">O significado da marca</p><h1 className="mt-3 max-w-4xl font-display text-4xl font-semibold leading-tight sm:text-6xl">Superlativo é o mais alto grau. Heureca é a solução encontrada.</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-white/75 sm:text-lg">Por isso, a proposta não termina em uma disciplina ou em uma série. O Universo Educacional Superlativo Heureca conecta aprendizagem, revisão, exploração, preparação para avaliações, ensino superior e produção acadêmica em uma mesma experiência.</p></section>
    <section className="mt-8"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-magenta">Jornada completa</p><h2 className="mt-1 font-display text-3xl font-semibold text-navy">Do primeiro som à pesquisa avançada</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{EDUCATION_LEVELS.map((level, i) => { const Icon = ICONS[i % ICONS.length]; return <article key={level.id} className="rounded-[1.4rem] bg-surface p-5 shadow-card"><span className="grid size-11 place-items-center rounded-xl bg-mist text-navy"><Icon className="size-5" /></span><h3 className="mt-4 font-display text-xl font-semibold text-navy">{level.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{level.description}</p></article>; })}</div></section>
    <section className="mt-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-magenta">Mapa de disciplinas</p><h2 className="mt-1 font-display text-3xl font-semibold text-navy">Todas as áreas podem entrar no catálogo</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{EDUCATION_AREAS.map((area) => <article key={area.id} className="rounded-[1.4rem] bg-white p-5 shadow-card"><h3 className="font-display text-xl font-semibold text-navy">{area.title}</h3><div className="mt-3 flex flex-wrap gap-2">{area.subjects.map((subject) => <span key={subject} className="rounded-full bg-paper px-3 py-1.5 text-xs font-semibold text-navy">{subject}</span>)}</div></article>)}</div></section>
    <section className="mt-10 rounded-[1.8rem] bg-blush p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-magenta">Suporte acadêmico</p><h2 className="mt-1 font-display text-3xl font-semibold text-navy">Da ideia à apresentação</h2><p className="mt-3 max-w-3xl text-muted">Apoio estruturado para organizar e desenvolver trabalhos acadêmicos com rigor, revisão e respeito à autoria do estudante.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ACADEMIC_SERVICES.map((item) => <div key={item.title} className="rounded-2xl bg-white p-4"><h3 className="font-semibold text-navy">{item.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted">{item.text}</p></div>)}</div><Link to="/trabalhos" className="mt-5 inline-flex items-center gap-2 font-semibold text-magenta">Abrir central acadêmica <ArrowRight className="size-4" /></Link></section>
  </div>;
}