import { Link, useRouterState } from "@tanstack/react-router";
import { Menu, Phone, X } from "lucide-react";
import { useEffect, useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { Button } from "@/components/ui/button";
import { NAV, SITE } from "@/lib/site";
import { cn } from "@/lib/utils";

export function SiteShell({ children }: { children: React.ReactNode }) {
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  const [open, setOpen] = useState(false);
  useEffect(() => setOpen(false), [pathname]);
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  return <div className="paper-grain flex min-h-dvh flex-col"><a href="#conteudo" className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-navy focus:px-3 focus:py-2 focus:text-white">Ir para o conteúdo</a>
    <header className="sticky top-0 z-40 border-b border-line bg-paper/90 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-3 px-4 sm:h-[4.25rem] sm:px-6"><Link to="/" className="min-w-0 shrink" aria-label="Página inicial Superlativo Heureca"><BrandMark /></Link><nav className="hidden items-center gap-1 lg:flex" aria-label="Principal">{NAV.map((item) => { const active = item.to === "/" ? pathname === "/" : pathname.startsWith(item.to); return <Link key={item.to} to={item.to} className={cn("rounded-lg px-3 py-2 text-sm font-semibold transition-colors duration-150", active ? "bg-navy text-white" : "text-ink/80 hover:bg-white hover:text-navy")}>{item.label}</Link>; })}</nav><div className="flex items-center gap-2"><Button asChild size="sm" className="hidden sm:inline-flex"><a href={SITE.whatsapp} target="_blank" rel="noreferrer">Inscreva-se</a></Button><button type="button" className="grid size-11 place-items-center rounded-xl text-navy lg:hidden" aria-expanded={open} aria-controls="menu-mobile" aria-label={open ? "Fechar menu" : "Abrir menu"} onClick={() => setOpen((v) => !v)}>{open ? <X className="size-5" /> : <Menu className="size-5" />}</button></div></div>{open ? <div id="menu-mobile" className="border-t border-line bg-paper px-4 py-4 lg:hidden"><nav className="flex flex-col gap-1" aria-label="Mobile">{NAV.map((item) => { const active = item.to === "/" ? pathname === "/" : pathname.startsWith(item.to); return <Link key={item.to} to={item.to} className={cn("rounded-xl px-4 py-3 text-base font-semibold", active ? "bg-navy text-white" : "text-ink hover:bg-white")}>{item.label}</Link>; })}<a href={SITE.whatsapp} target="_blank" rel="noreferrer" className="mt-2 inline-flex h-12 items-center justify-center rounded-xl bg-magenta px-4 font-semibold text-white">Falar no WhatsApp</a></nav></div> : null}</header>
    <main id="conteudo" className="flex-1">{children}</main>
    <footer className="mt-auto"><div className="bg-magenta px-4 py-3 text-center text-sm font-bold uppercase tracking-[0.12em] text-white sm:text-[0.92rem]">Superlativo Heureca — {SITE.slogan}</div><div className="bg-navy-deep text-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 py-10 sm:px-6 md:grid-cols-3"><div><BrandMark light /><p className="mt-4 max-w-xs text-sm leading-relaxed text-white/75">Aprendizagem integral, aulas dinâmicas, preparação para provas, exploração com IA e orientação acadêmica — da alfabetização ao Ensino Superior.</p></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">Proposta</p><ul className="mt-3 space-y-1.5 text-sm text-white/85"><li>Alfabetização → Ensino Superior</li><li>ENEM → Vestibulares → Concursos</li><li>RAG + IA + exploração pedagógica</li></ul></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">Inscrições</p><a href={`tel:${SITE.phoneTel}`} className="mt-3 flex items-center gap-2 text-lg font-bold tabular-nums tracking-tight"><Phone className="size-4" />{SITE.phoneDisplay}</a><p className="mt-2 text-sm text-white/70">PV particular ou WhatsApp. {SITE.invite}</p><a href={SITE.facebook} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-gold underline-offset-4 hover:underline">Grupo no Facebook</a></div></div><p className="border-t border-white/10 px-4 py-4 text-center text-xs text-white/50">© {new Date().getFullYear()} {SITE.legal} ®. Todos os direitos reservados.</p></div></footer>
  </div>;
}